import { supabase } from '../supabase';
import fs from 'fs';
import path from 'path';

/**
 * Executes a SQL migration file against the Supabase database
 * @param sqlFilePath Path to the SQL file to execute
 */
export const executeSqlMigration = async (sqlContent: string): Promise<void> => {
  try {
    console.log('Executing SQL migration...');
    const { error } = await supabase.rpc('exec_sql', { sql: sqlContent });
    
    if (error) {
      console.error('Migration error:', error);
      throw error;
    }
    
    console.log('Migration completed successfully');
  } catch (error) {
    console.error('Failed to execute migration:', error);
    throw error;
  }
};

/**
 * Checks if the forum_replies table exists and creates it if it doesn't
 */
export const ensureForumRepliesTable = async (): Promise<void> => {
  try {
    // Check if table exists
    const { data, error } = await supabase
      .from('forum_replies')
      .select('id')
      .limit(1);
    
    if (error && error.code === '42P01') { // Table doesn't exist
      console.log('forum_replies table does not exist, creating it...');
      
      // Read the SQL file
      const sqlContent = `
      -- Create forum_replies table if it doesn't exist
      CREATE TABLE IF NOT EXISTS forum_replies (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        thread_id BIGINT NOT NULL,
        author_id UUID NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ
      );
      
      -- Create index for faster queries
      CREATE INDEX IF NOT EXISTS forum_replies_thread_id_idx ON forum_replies(thread_id);
      CREATE INDEX IF NOT EXISTS forum_replies_author_id_idx ON forum_replies(author_id);
      
      -- Enable Row Level Security
      ALTER TABLE forum_replies ENABLE ROW LEVEL SECURITY;
      
      -- Create policies
      CREATE POLICY "Anyone can view forum replies"
        ON forum_replies
        FOR SELECT
        USING (true);
      
      CREATE POLICY "Authenticated users can insert their own replies"
        ON forum_replies
        FOR INSERT
        WITH CHECK (auth.uid() = author_id);
      `;
      
      // Execute the SQL
      await executeSqlMigration(sqlContent);
      console.log('forum_replies table created successfully');
    } else {
      console.log('forum_replies table already exists');
    }
  } catch (error) {
    console.error('Error ensuring forum_replies table:', error);
  }
};
