-- Create forum_replies table if it doesn't exist
CREATE TABLE IF NOT EXISTS forum_replies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL REFERENCES forum_threads(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS forum_replies_thread_id_idx ON forum_replies(thread_id);
CREATE INDEX IF NOT EXISTS forum_replies_author_id_idx ON forum_replies(author_id);

-- Enable Row Level Security
ALTER TABLE forum_replies ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Anyone can view forum replies"
  ON forum_replies
  FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can insert their own replies"
  ON forum_replies
  FOR INSERT
  WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Users can update their own replies"
  ON forum_replies
  FOR UPDATE
  USING (auth.uid() = author_id);

CREATE POLICY "Users can delete their own replies"
  ON forum_replies
  FOR DELETE
  USING (auth.uid() = author_id);

-- Create trigger to update the replies_count in forum_threads
CREATE OR REPLACE FUNCTION update_thread_replies_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE forum_threads
    SET replies_count = replies_count + 1
    WHERE id = NEW.thread_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE forum_threads
    SET replies_count = replies_count - 1
    WHERE id = OLD.thread_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_thread_replies_count_trigger ON forum_replies;
CREATE TRIGGER update_thread_replies_count_trigger
AFTER INSERT OR DELETE ON forum_replies
FOR EACH ROW
EXECUTE FUNCTION update_thread_replies_count();
